version: "3.9"
services:
  frontend:
    build:
      context: ./frontend/fake-news
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - frontend:/usr/frontend
  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile
    ports:
        - 8983:8983
    volumes:
        - backend:/usr/backend

volumes:
  backend: {}
  frontend: {}
